twig:
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        societe_info: '@App\Service\societeService'
        notify_number: '@App\Service\NotifyService'

when@test:
    twig:
        strict_variables: true
